### ISSUE TITLE
Use lxd metadata 

### ISSUE THREAD

**Issue by dridk** [REGOVAR/Pirus#16]
Plugin information should be embedded in the metadata of lxd. 
It will provide one package with all inside

**Comment by ikit** [comment]
Not agree to merge our manifest.json with the metadata.json of the lxc container.
In addition, the workflow is more simple (to create and to install package) when the 2 files are separeted.

**Comment by dridk** [comment]
for the end user, the plugin should be only one file called : xxxx.tar.gz. No matter how you save plugin information. Everything should be in th package. 
From my point of view, I prefere keep all data in the same place. But as you want.
