### ISSUE TITLE
Set fixed PATH

### ISSUE THREAD

**Issue by dridk** [REGOVAR/Pirus#38]
Input; output, db path should not be customizable. 
use by defaut : 

```
 /pirus/input
 /pirus/output
 /pirus/db 
```

**Comment by ikit** [comment]
container are fully customizable. if the user don't want to customize it, he can take the default pirus pipeline package. No time to implement and set up several behavior for that.

**Comment by dridk** [comment]
This is not asigned to you

**Comment by ikit** [comment]
duplicate with #42
