### ISSUE TITLE
CLI syntax

### ISSUE THREAD

**Issue by dridk** [REGOVAR/Pirus#83]
Do you have a wiki page to write CLI Command ? 

     pirus --version 
     pirus --help
     pirus pipeline list 
     pirus pipeline show <id> 
     pirus pipeline rem <id> 
     ...

**Comment by ikit** [comment]
cli api is not yet implemented

I just create the wiki page : https://github.com/REGOVAR/Pirus/blob/master/docs/cliapi.rst
Thanks to put your ideas inside.

**Comment by dridk** [comment]
Cannot edit : here is better, to comment :  

```
pirus version : return version
pirus help  : return help
pirus pipelines help : return pipeline help 
pirus pipelines list [filters]: return list of pipeline avaible 
pirus pieplines show <name> : return information of pipeline <name>
pirus pipelines rem <name> : uninstall a pipeline 
pirus pieplines add <path> : install a new pipeline 
pirus [runs] list [filters] : show list of runs  
pirus [runs] stop <id> : stop a run 
pirus [runs] pause <id> : pause a run 
pirus [runs] start <pipeline> --input <path> --output <path> --config <config>
prius [runs] show <id> : show run information 
pirus [runs] inputs <id> : show files input 
pirus [runs] outputs <id> : show files output
pirus [runs] logs <id> : show run log 
pirus [runs] cd <id> : Change directory to the current run 
pirus config : set pirus configuration 
```

**Comment by ikit** [comment]
Hi, the "minimum version of pirus cli is done". below the todo list of the implementation:
- [x] pirus version : return version
- [x] pirus help  : return help
- [x] pirus pipelines help : return pipeline help 
- [x] pirus pipelines list : return list of pipeline avaible 
- [ ] pirus pipelines list [filters]: return list of pipeline avaible 
- [x] pirus pipelines show <id> : return information of pipeline <id>
- [x] pirus pipelines uninstall <id> : uninstall a pipeline 
- [x] pirus pipelines install <path> : install a new pipeline 
- [x] pirus job list : show list of jobs  
- [ ] pirus job list [filters] : show list of jobs  
- [x] pirus job stop <id> : stop a job
- [x] pirus job pause <id> : pause a job 
- [x] pirus job start <id> : restart a job that have been paused
- [x] pirus job new "<name>" <pipeline_id> -i [file_id] -f [<file_path>] -c <config_path>
- [x] prius job show <id> : show job information 
- [ ] pirus job inputs <id> : show files input 
- [ ] pirus job outputs <id> : show files output
- [ ] pirus job logs <id> : show run log 
- [ ] pirus job cd <id> : Change directory to the current run 
- [x] pirus config : show pirus configuration 
- [ ] pirus config <field> <value>: set pirus configuration 
- [x] pirus file list : show list of file registered in pirus
- [ ] pirus file list [filter]: show list of file registered in pirus
- [x] pirus file show <id>: show metadata about the file
- [ ] pirus file <id> : get path to the file
- [x] pirus file add <path> : register a new local file into pirus
- [ ] pirus file add <remote_url> : register a new remote file to pirus
- [ ] pirus file rem <id> : remove file from pirus

**Comment by ikit** [comment]
Close issue as minimum requiered is implemented. next features tracked in the issue #109
